### ISSUE TITLE
Release 6.0.0 todo's

### ISSUE THREAD

**Issue by doozMen** [dooZdev/Highway#48]
* [x] use stencil directly to generate pre-push and github action code
* [x] add github action script #47 
* [x] update buildtools and github actions to sync changes #47
* [x] run on linux
